/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Complaint {
  complaintId?: number;
  complaintText?: string;
  status?: 'OPEN' | 'CLOSED';
}
