/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Feedback {
  feedbackId?: number;
  feedbackText?: string;
  feeling?: 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
  ratingValue?: number;
}
