/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Trainer } from '../models/trainer';
import { User } from '../models/user';
export interface Message {
  content?: string;
  timestamp?: string;
  trainer?: Trainer;
  user?: User;
}
