/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Rating {
  comment?: string;
  createdAt?: string;
  ratingId?: number;
  ratingValue?: number;
}
