/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Segment {
  durationType?: 'MINUTES' | 'HOURS';
  durationValue?: number;
  intensity?: string;
  segmentId?: number;
  segmentName?: string;
}
