/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Trainer {
  active?: boolean;
  email?: string;
  experienceLevel?: string;
  firstName?: string;
  lastName?: string;
  password?: string;
  specialization?: string;
  trainerId?: number;
  verified?: boolean;
}
