/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TrainerDto {
  email: string;
  experienceLevel: string;
  firstName: string;
  lastName: string;
  password: string;
  specialization: string;
}
