/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  age?: number;
  email?: string;
  firstName?: string;
  fitnessLevel?: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  goal?: string;
  lastName?: string;
  password?: string;
  userId?: number;
}
