/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserChangeDto {
  age: number;
  firstName: string;
  fitnessLevel: string;
  goal?: string;
  lastName: string;
}
