/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AdminDto } from './models/admin-dto';
export { Complaint } from './models/complaint';
export { Feedback } from './models/feedback';
export { LoginDto } from './models/login-dto';
export { LoginResponseDto } from './models/login-response-dto';
export { Message } from './models/message';
export { PageableObject } from './models/pageable-object';
export { PageComplaint } from './models/page-complaint';
export { PageTrainer } from './models/page-trainer';
export { PageUser } from './models/page-user';
export { Rating } from './models/rating';
export { Segment } from './models/segment';
export { SortObject } from './models/sort-object';
export { Trainer } from './models/trainer';
export { TrainerDto } from './models/trainer-dto';
export { Training } from './models/training';
export { User } from './models/user';
export { UserDto } from './models/user-dto';
