/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserControllerService } from './services/user-controller.service';
export { TrainerControllerService } from './services/trainer-controller.service';
export { AuthContorllerService } from './services/auth-contorller.service';
export { MessageControllerService } from './services/message-controller.service';
export { AdminControllerService } from './services/admin-controller.service';
