/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Message } from '../../models/message';

export interface GetChatHistory$Params {
  userUsername: number;
  trainerName: number;
}

export function getChatHistory(http: HttpClient, rootUrl: string, params: GetChatHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Message>>> {
  const rb = new RequestBuilder(rootUrl, getChatHistory.PATH, 'get');
  if (params) {
    rb.query('userUsername', params.userUsername, {});
    rb.query('trainerName', params.trainerName, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Message>>;
    })
  );
}

getChatHistory.PATH = '/chat/history';
