/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Message } from '../../models/message';

export interface SendMessageFromTrainerToUser$Params {
  userUsername: number;
  content: string;
}

export function sendMessageFromTrainerToUser(http: HttpClient, rootUrl: string, params: SendMessageFromTrainerToUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Message>> {
  const rb = new RequestBuilder(rootUrl, sendMessageFromTrainerToUser.PATH, 'post');
  if (params) {
    rb.query('userUsername', params.userUsername, {});
    rb.query('content', params.content, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Message>;
    })
  );
}

sendMessageFromTrainerToUser.PATH = '/chat/trainerToUser';
